### ISSUE TITLE
Tracking issue for `ComitLN` swarm tasks

### ISSUE THREAD

**Issue by tcharding** [comit-network/comit-rs#2408]
## Problem

During the LN squad we hacked together a network behaviour to get the job done (Han-HALight swap for ether <-> BTC).  We took a few short cuts that need to be remedied in order to scale out to other protocol pairs (and HALight-Han even).

We are not totally convinced with the way we are using the libp2p abstractions (`NetworkBehaviour`, `ProtocolsHandler`, `OneShotHandler` etc).  We have a [ticket](https://github.com/comit-network/comit-rs/issues/2388) that suggests re-writing the `ComitLN` behaviour (and at the same time writing a HALight-HErc20 behaviour).  

This ticket is to track work that will need to be considered when scaling out to all the supported protocol pairs.  It was created from all the `TODO/FIXME` comments in `comit_ln.rs` written during the LN squad sessions.

## Considerations

- [x] The `NetworkBehaviour` is for all peers, currently we have a bunch of hash maps to save swap data shared by the communication protocols.  We key on `NodeLocalSwapId` and on `SwapId`.  This all needs re-thinking.
- [x] The connector fields are Ethereum only, Bitcoin will need to be added.
- [ ] The swap seed is derived from a root seed stored in the behaviour.  This is better than it is currently done for rfc003, we should make this uniform and use best security practices i.e., secret derived from information fully controlled by the local node (i.e., `NodeLocalSwapId` not the shared `SwapId`).
- [x] The `CommunicationState` only models Han-HALight
- [x] Re-visit the naming of 'created' and 'finalized' swap incl. the function names `get_finalized_swap()`
- [ ] Re-consider the types used by the oneshot protocols
```
// TODO: The logic of deciding what identity is which is also present in
// impl NetworkBehaviourEventProcess<oneshot_behaviour::OutEvent<finalize::
// Message>> for ComitLN {     fn inject_event(&mut self, event:
// oneshot_behaviour::OutEvent<finalize::Message>) There should one
// place of truth

// TODO: To avoid mistakes here, we should create different types for incoming
// and outgoing identities This is best done on the libp2p-protocol
// level as we already differentiate there between Inbound and Outbound upgrades
```
- [x] Remove all hardcoded Ethereum ledger and network stuff
- [x] Work out what we are going to do with the data of a 'finalized' swap.  There is an [issue](https://github.com/comit-network/comit-rs/issues/2391) to add this data to the database.  Once that is done we can decide if we want to pass this data around or just let everyone get it from the database when needed.  Consider removing `FinalizedSwap` and/or redesigning it incl. re-naming the fields (do we really want to stick with the alpha/beta terminology?). 
- [x] Remove usage of the global `tokio::task::spawn` function
- [x] When receiving an announcement, if digest is not present, consider saving it to some other kind of hashmap/hashset.
- [x] Failed swap is per peer, we do not know which swap it was.  In general we need to consider how multiple swaps between two peers will work.
- [x] Consider reading/verifying the LND TLS cert when a request comes in on the REST API instead of in the network behaviour (so we don't hit the `expect() calls`).
- [ ] Correctly utilise `start_of_swap`, this is not handled at all currently.
- [ ] Use `EtherHtl` from blockchain contracts to to generate the `HtlcParams`

**Comment by thomaseizinger** [comment]
I think we can close this for now, most of the things have been tackled in https://github.com/comit-network/comit-rs/pull/2689.
