### ISSUE TITLE
ERC20 Tracking issue

### ISSUE THREAD

**Issue by thomaseizinger** [comit-network/comit-rs#271]
Tasks:

- [x] HTLC for ERC20 swap (#270) (@D4nte finishes this)
~~Tests for ERC20 token contracts with call return 0 (e.g. PAY) (@thomaseizinger) (#273)~~
- [x] Test for unsuccessful contract deployment on failure in `transferFrom` (@thomaseizinger) (#272)
- [ ] More tests in `EthereumService`
- [x] Use Erc20Htlc in production code
   - [x] Use ganp instead of HTTP for communication between COMIT nodes (@LLFourn) (#280)
- [x] Replace GanacheClient with ParityClient in HTLC tests (@thomaseizinger) (#279)
- [x] Create stories for LQS update
- [x] Design `Asset` trait implementation for ERC20

Child of #399.
Child of #408.
