### ISSUE TITLE
Open source administration tasks

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#283]
- [x] Complete open-source milestone (https://github.com/tenx-tech/swap/milestone/4)
- [x] Move to COMIT organization
- [x] Rename repository to comit-rs
- [x] Bring readme links up2date (#233, #366)
- [x] Update comit.network website to point to github repository (just need to merge  https://github.com/tenx-tech/COMIT_website/pull/1 )
- [x] Add test coverage
- [x] Add an open source license in README.md including a license file (#366)
- [x] Cleanup old unneeded branches
- [x] Merge the Open Source cleanup branch: #366  
- [x] Host blog on Github pages
- [x] Activate/Move Travis to CoBloX GitHub organisation

Child of #407.
