### ISSUE TITLE
Use BIP32 for generation of keys to be used in HTLCs

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#290]
**Summary** 
Use BIP32 to create a new address for each bitcoin & ethereum HTLC created by the exchange_service

**Detailed**

Currently we use pre-configured addresses to generate the bitcoin & ethereum HTLC. Instead, we will generate a unique key using bip32 libraries that will be use for the current trade only.

**Task list**
- [ ] make bip32 ledger generic
- [ ] use bip32 for bitcoin HTLCs
- [ ] use bip32 for ethereum HTLCs
