### ISSUE TITLE
Proceed with sanity checks and analysis of Bitcoin LQS output

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#302]
**Summary** 
Currently, in `json_config`, `comit_node` blindly trusts the transactions returned by the Bitcoin Ledger Query Service. Moreover, the bitcoin htlc funding `vout` is assume to be `0` (`1` being the change).

`json_config` should be updated to analyze the transaction returned by bitcoin LQS, ensure that the funding transaction is correct and extract the correct `vout`

**Open question**
* What checks are needed? Correct amount, number of confirmations (need to update Ledger Query Service for that, see #303 )
* What happens if it's over funded?

**Task list:**
- [x] Check that amounts sent to htlc is as expected
- [x] Extract funding `vout` from the transaction and use it
- [ ] Write an end to end test that checks that the thing doesn't go through if it's under funded.
