### ISSUE TITLE
Tracking issue for state machine based implementation of BTC-to-ETH

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#346]
- [x] Implement alice state machine
- [x] Implement alice actions (what to do next)
- [x] Implement persistence abstraction
- [x] Merge existing branch (requires reverting non-working stuff) (#348)
- [x] Implement queries for state machine (wait for HTLC funding/redeem/refund) (#373)
- [x] Implement bob state machine (#350)
- [x] Implement bob actions (#360)
- [ ] Implement `IsContainedInTargetLedgerTransaction` for EtherQuantity (validates the right amount of Ether is present in funding tx)
- [x] Implement `NewSourceHtlcRefundedQuery` for `BitcoinQuery` (done in #396)
- [x] Implement `NewSourceHtlcRedeemedQuery` for `BitcoinQuery` (done in #396)
- [ ] Implement `NewTargetHtlcRefundedQuery` for `EthereumQuery`
- [ ] Implement `NewTargetHtlcRedeemedQuery` for `EthereumQuery`
- [ ] Implement new API endpoints #380
- [ ] Adapt HTTP path tests to new API

Child of #405.
Child of #408.
