### ISSUE TITLE
Check-in EVM hex code & remove generation

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#606]
Motivations:
- Contract ethereum hex should be static and part of RFC003
- Generation of the hex from EVM assembly should be easy but **not** part of the comit-rs crate

DoD:
- [ ] ~One private new repository for all HTLCs in coblox (coblox/blockchain_contracts#1 & coblox/blockchain_contracts#3)~ new vendor crate `blockchain_contracts` #864
- [x] Commit EVM hex code in `comit_node` crate #636 
- [x] remove build.rs from comit-rs repo (3 reviews)
- [x] create new tooling repo with templates to facilitate EVM compilation #864
- [x] Some way to get offsets and full hex for particular HTLC (see table in RFCs) for Ethereum #864
- [ ] Offsets for Bitcoin #910 #932 #933 
- [x] Compare with RFCs (and update the latter one if needed) for Ethereum (done, see comit-network/RFCs#46 & comit-network/RFCs#48)
- [ ] Compare with RFCs for Bitcoin #910
- [x] Make offsets in RFCs: start index inclusive and end index exclusive for Ethereum comit-network/RFCs#66
- [ ] Make offsets in RFCs: start index inclusive and end index exclusive for Bitcoin
- [ ] Tests are running
- [ ] Upgrade to latest solc
- [ ] use fix offsets in comit-rs #636 #933 
- [ ] Move crate to own repo

~~Blocked by coblox/COMIT-RFCs#7~~ (closed)
~~Blocked by comit-network/RFCs#21~~ (closed)

**Comment by D4nte** [comment]
Parity uses `solc`/`solcjs`: https://github.com/paritytech/rust_solc

**Comment by D4nte** [comment]
Can't find Rust lib to compile evm assembly/solidity..

**Comment by bonomat** [comment]
> General question: What is is so bad about the docker requirement? Docker is pretty much a thing that all developers have installed, no? :D

exactly, it's only `pretty much a thing that all developers have installed`. Imho it shouldn't be required if you just want to build our code base. As we saw during your hackathon: not everyone has Docker installed.

**Comment by thomaseizinger** [comment]
The hackathon is a completely different environment.

If you want to build things from source, you expect having to install all kinds of stuff, esp. if you are building a project that compiles for your current architecture (like Rust projects do). Codebases that use languages like Java are different and usually much easier to build.

We already require users to install `libzmq`, `yarn` and `nvm` if the want to build from source and requiring `docker` as well is bad? I don't understand that reasoning :)

**Comment by bonomat** [comment]
As you are saying, we need all kind of stuff for our build like `libzmq`. The rest is actually only needed for our end2end tests. Docker should not be required for the build imho as we only use docker to make use of other tools, i.e. `solc`.

**Comment by thomaseizinger** [comment]
Having talked with @LLFourn and @D4nte offline, we agreed that eventually, this will be solved because the HEX code is specified in the RFC and not build on-demand. We therefore rephrased the issue to reflect what should actually be done: checking in the EVM byte code into the repository and embed it into the application. Not requiring `docker` is a side-effect of that and thus doesn't require additional attention :)

**Comment by D4nte** [comment]
Yes please not the issue is updated and need to be re-groomed.

**Comment by D4nte** [comment]
Work was started on https://github.com/comit-network/comit-rs/tree/606-build-evm-code-on-demand before it got blocked due to a change of strategy.

Now that the strategy is clarified and unblocked, I'd like to be the one to finish the change and to take over from where I left it.

**Comment by D4nte** [comment]
@luckysori, you are my hero 🦸‍♀️ and savior ⚔️

**Comment by thomaseizinger** [comment]
The actual epic is achieved. I moved https://github.com/coblox/blockchain-contracts/issues/4 to another epic that tracks all the `internal` folder stuff.
