### ISSUE TITLE
Remove all path dependencies from `cnd` and `btsieve` (i.e. get rid of the `internal/` folder)

### ISSUE THREAD

**Issue by bonomat** [comit-network/comit-rs#626]
Motivation: 
* being able to release comit-rs as a crate
* a smaller dependency footprint and hence faster compile-times + better IDE performance
Problem: must not have path dependencies, must not have git repo dependencies.

---

Ideas:

- [x] `secp256k1_support`.
- [x] `bitcoin_support`: #1564.
- [x] `blockchain_contracts`.
- [x] `bitcoin_witness`.
- [x] `tc_bitcoincore_client`: Is it actually used? In any case, inline it. https://github.com/comit-network/comit-rs/pull/1568
- [x] `tc_web3_client`: Is it actually used? In any case, inline it. https://github.com/comit-network/comit-rs/pull/1568
- [x] `siren`: Publish as standalone crate: #1297.
- [x] `comit_i`: To be removed: #1558.
- `libp2p-comit` can stay in comit-rs repo for the time being.
- [x] key_gen: To be removed: #1520.

### `ethereum_support`

- [ ] Use `contract-address` from parity: https://github.com/comit-network/comit-rs/issues/1317
- [ ] The `network` module might be obsolete with https://github.com/comit-network/RFCs/issues/73
- [ ] `ether_quantity`/`erc20_quantity`/`erc20_token` and `u256_ext` should be moved into cnd
