### ISSUE TITLE
Lightning Bitcoin swaps using lnd

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#908]
Focus has alpha ledger (the hard part).

- [ ] Connect comit_node to lnd (configuration, test setup) #911
  - [ ] Create `/health` endpoint on comit_node that would do a `getinfo` to lnd and return health check #911
- [ ] Implement create swap for ln on Alice: DoD -> appears in `/swaps` #912 & #913
- [ ] Forward swap request to Bob when creating it and Bob reject it (automatic because error) #914
- [ ] Bob receives bam swap request and it appears in  bob `/swaps` #915
- [ ] Bob can decline and sends message to Alice, swaps shows as declined on both Alice and Bob
- [ ] "create hold invoice" action is displayed on Bob after receiving swap
- [ ] Bob use lnd to watch for invoices and show accept action when invoice is created on ln
- [ ] Bob shows "cancel invoice" action when hold invoice was created and mark swap as declined if invoice is cancelled.
- [ ] Bob can accept and it sends message to Alice over bam. Swap shows as "accepted' on both sides
- [ ] Alice shows "fund" action if swap is accepted
- [ ] Alice watches for payment send from her lnd and show no action
- [ ] Bob watches invoice payment and display fund beta action
- [ ] Bob watches fund beta action, when done, Alice displays redeem action
- [ ] Bob watch beta redeem, learns secret, show alpha redeem action (lnd settle invoice with secret)
- [ ] Once invoice is settled, both parties shows party is done
- [ ] Check/test Beta refund works as usual

**Comment by bonomat** [comment]
Closing this as all sub-tickets have been closed already.
