### ISSUE TITLE
Bobtimus Prime

### ISSUE THREAD

**Issue by D4nte** [comit-network/comit-rs#916]
TODO: Spend a bit more time to make it a proposal.

---

Basic features:
- CLI daemon
- Accepts any trade
- Does the blockchain actions
- Display trades that happened
- Accept trades within a given rate range

Config file:
- comit_node http api endpoint
- Ethereum wallet access with money
- Access to Ethereum network to broadcast transactions
- Bitcoin wallet access with money
- Access to Bitcoin network to broadcast transactions
- Connection to lnd with money

Advanced features:
- create links and post them on Slack

---
What language?
- TypeScript: typed language that allows easy consumption of http API, based on popular language JavaScript. Allow synergy with comit-i development.
- JavaScript: see TS but not type and more popular
- Python: most popular dynamic language.
- Rust: best language
=> TypeScript mainly for the synergy with comit-i

- [x] Build a daemon that can connect to comit_node and trigger  POST `/accept` on any trade within a rate range and `/decline` on any other. Own repo. most primitive test framework.
- [x] Bitcoin wallet coblox/bobtimus#3
- [x] Ethereum wallet coblox/bobtimus#6
- [x] Triggers all actions using wallets coblox/bobtimus#4
- [x] Be able to provide a mnemonic (config file) coblox/bobtimus#11
- [x] Test against comit-rs (manual test + demo setup instructions) coblox/bobtimus#12

Not needed for Demo:
- [x] Display Ethereum address + First unused Bitcoin address when starting node
- [ ] Refund

**Comment by bonomat** [comment]
Shall we go for an inmemory only wallet for ethereum, i.e. not using parity for that?

**Comment by D4nte** [comment]
> Shall we go for an inmemory only wallet for ethereum, i.e. not using parity for that?

Sure, no idea how easy/hard it is...

**Comment by bonomat** [comment]
> > Shall we go for an inmemory only wallet for ethereum, i.e. not using parity for that?
> 
> Sure, no idea how easy/hard it is...

should be easy, we are doing something similar in comit-rs already, i.e. we just need to keep track of the `account` + `nonce` and have an in-memory key to sign transaction. 

Main reason: I would like to not depend on a parity node for this feature.

**Comment by D4nte** [comment]
Putting back to new so we can decide where to go from here.

**Comment by thomaseizinger** [comment]
> Putting back to new so we can decide where to go from here.

Once it is open source we should move it to the appropriate repository.

**Comment by D4nte** [comment]
> > Putting back to new so we can decide where to go from here.
> 
> Once it is open source we should move it to the appropriate repository.

What is `it`. I'd hope we close this Epic now and consider the quaterly goal achieved.

**Comment by D4nte** [comment]
`ts-node` is fine for now.
Once refund implemented coblox/bobtimus#20, we can consider this Epic/Goal achieved!
